### ISSUE TITLE
Namespace / Missing reference error in the Ifc.NET library

### ISSUE THREAD

**Issue by pagumakwana** [CAFM-Connect/Ifc.NET#3]
Hello Klacol

Seems you have created a good library for reading ifcxml files. Though i am unable to use it after adding via nuget package. I get this error while building project on the following line - 

using Ifc4; 

Error	4	The type or namespace name 'Ifc4' could not be found (are you missing a using directive or an assembly reference?)	

Have tried adding references as well. Can you help here?

**Comment by klacol** [comment]
Hi Pragnesh, 

thank you for the info. I can reproduce that. There is an error with the nuget package (Install-Package Ifc.NET). I will fix with the next release. Until then you can check out this repo and work with the class lib directly as a project reference in your solition.
